import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { useEffect, useState } from 'react';

type Item = {
  title?: string;
};

const Home: NextPage = () => {
  const [item, setItem] = useState<Item>({});
  useEffect(() => {
    fetch('/api/hello')
      .then((response) => response.json())
      .then((item) => setItem(item));
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js</a> in Firebase!
        </h1>

        <p className={styles.description}>
          {!item?.title ? (
            'Loading data from /api/hello...'
          ) : (
            <>
              {item?.title} (from <code>/api/hello</code>)
            </>
          )}
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
